spring:
  config:
    import: optional:classpath:/2022-MyRSS-secret/application.yml

  profiles:
    active: test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          time_zone: Asia/Seoul
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    redis:
      repositories:
        enabled: false

  redis:
    host: localhost
    port: 6379
    password:

  session:
    store-type: redis

server:
  tomcat:
    max-connections: 400
    accept-count: 50
    threads:
      min-spare: 10
      max: 10

oauth:
  github:
    accessTokenUrl: https://github.com/login/oauth/access_token
    userInfoUrl: https://api.github.com/user
    clientId:
    clientSecret:

logging:
  level:
    web: debug

